[mypy]
python_version = 3.11
strict = True
plugins = pydantic.mypy


follow_imports = normal
ignore_missing_imports = True


disable_error_code = import-untyped, import-not-found, ignore-without-code


warn_return_any = True
warn_unused_configs = False
disallow_untyped_defs = True